### ISSUE TITLE
pypy compatability

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/wakfu-utils#8]
Any chance you can drop the msgspec requirement to get this running on pypy? Majority of the runtime is spent doing things pypy should be faster at.

**Comment by mikeshardmind** [comment]
I'll consider it.

Things currently relying on msgspec (msgspec.Struct and msgspec.msgpack)

- item data (msgspec.Struct and msgspec.msgpack)
- stats classes (msgspec.Struct)
- message passing between us and wakforge (msgspec.msgpack)


First two I'm mostly unopposed to changing given a specific benefit
Last one will likely require handrolling some msgpack handling (pyodide (and by extension wakforge) can't use msgpack wheels iirc) Since the majority of the users of this are using it through wakforge, breaking that isn't going to work.

Will also need to see if we're using any python3.11 exclusive syntax, as pypy's latest supported python version is still 3.10

**Comment by mikeshardmind** [comment]
I've started working on this, should also make a native implementation easier later having a reference implementation like this.

**Comment by mikeshardmind** [comment]
resolved in 51c54d3

initial results show pypy is slower (~1.2s) for a single solve. between jit warmup time, and how much this has been optimized already, this isn't fully surprising, but I didn't extensively look into this.

This is technically also compatible with Graalpy now, which I did not do any testing of.

Cost of the changes is low, and I don't mind being rid of the msgspec dependency.
